services:
  db:
    image: postgres:16
    container_name: chimu_db
    environment:
      POSTGRES_DB: "chimu"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "277353"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    restart: unless-stopped
    volumes:
      - chimu_db:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
volumes:
  chimu_db: